### ISSUE TITLE
enum values is translated into numbers

### ISSUE THREAD

**Issue by XavierCHN** [TypeScriptToLua/TypeScriptToLua#1006]
```Typescript
let foo = modifierfunction.MODIFIER_EVENT_ON_ATTACK;
```
is translpiled to
```Lua
foo = 166
```
when declared const enum
```Typescript
declare const enum modifierfunction {
    // other keys
    MODIFIER_EVENT_ON_ATTACK = 166
}
```
which is supposed to be `foo = MODIFIER_EVENT_ON_ATTACK `

Tested in typescript-to-lua^0.36.0

**Comment by lolleko** [comment]
This is by design. Remove the const in the declaration to get

`foo = modifierfunction.MODIFIER_EVENT_ON_ATTACK`

Typescript playground: 

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3iFBXAtvAMKqYAqIm8A3gFDwPwBmSS8AvPAIwBMAzLQC+tWqEiwEOAsQpU6jZqw7d+QkRBBZk6DACFYykjtkYAdCyQBuWhqwAjA5xPnWloA

TSTL playground:

https://typescripttolua.github.io/play#code/CYUwxgNghgTiAEYD2A7AzgF3iFBXAtvAMKqYAqIm8A3gFDwPwBmSS8AvPAIwBMAzLQC+tWqEiwEOAsQpU6jZqw7d+QkRBBZk6DACFYykjtkYAdCyQBuWhqwAjA5xPnWloA

**Comment by XavierCHN** [comment]
what if I want to make it `foo = MODIFIER_EVENT_ON_ATTACK` but not `foo = modifierfunction.MODIFIER_EVENT_ON_ATTACK`

is it means that I have to declare MODIFIER_EVENT_ON_ATTACK as a constant like `declare const MODIFIER_EVENT_ON_ATTACK = 166`? while MODIFIER_EVENT_ON_ATTACK is provided by the engine?
but that will break the return declarations by other API since there is something like
```
declare interface CDOTA_Modifier_Lua {
     /**
     * Return a list of modifier functions this modifier implements.
     */
    DeclareFunctions?(): modifierfunction[];
}
```

**Comment by Perryvw** [comment]
We have a special annotation for that: `@compileMembersOnly`: https://typescripttolua.github.io/docs/advanced/compiler-annotations#compilemembersonly

This was used on the old dota declarations, but seems like some update changed how enums are defined. I am planning to fix the latest dota types soon.
