### ISSUE TITLE
[Question] Is `import * as ...` work as indended?

### ISSUE THREAD

**Issue by Toliak** [TypeScriptToLua/TypeScriptToLua#1019]
**Description**

For example, there is a TS file with some exported functions.
When I import it via `import * as alphas from '...'` and call a function (e.g. `alphas.test()`), I expect `alphas.test()` will be generated. However, the transpiled result is `alphas:test()`.

Is that transpiling correct?

Docs (there are no `:` in function call): [Lua module `require`](http://lua-users.org/wiki/ModulesTutorial)

**Example**

See [playground](https://typescripttolua.github.io/play#code/PQKgUAMgpgLgBAcgEawIYLiuq4wJ4AOUAzgMYBOAlgfALYD2AJgK4A2UwAZpe8AO4ALVDCgA3KOTh9KMAXE7MAdqRiV6iuFAAeBeuRgAuMGG2798pSrUaRxGAAoAlAbij6lRgG5jAOXpx2GARiOEpaM3hUVlZNHT0RRk1FVVUSeXJ6WkQUGHRQ5P8EKIIhYgQAOmMAEWYoXH8BGBgCA2BgVmZUAFpmYglicr0Ac35KAGtKYABZJjYSABVmGD1KKLgwAElYohVcIUjWEtQB2wdHKR4YrBhyVEViAh4oRMoC7EPS8tOnOHsUUlQvTqsgkdUoIUU-j6rE4jjAcBAwGMYQiCOwIWKpXSmWyaAQ3jAmOOXxIZyAA)

![image](https://user-images.githubusercontent.com/25643405/118392355-00a76800-b642-11eb-8e46-5261eecf97a4.png)

**Comment by Perryvw** [comment]
This seems to work as intended. You should write declarations for the functions so TypeScript understands what you are importing: https://typescripttolua.github.io/docs/advanced/writing-declarations/

So in your project you would have a file `beta.d.ts`:
```
export declare function test(): void;
```

Part of the declarations is if function have a 'self parameter' or not, if they do, `:` will be used, `.` otherwise. See https://typescripttolua.github.io/docs/the-self-parameter for more information.

If you don't want the self parameter you can update the declarations to:
```
/** @noSelf */
export declare function test(): void;
```

Generally if you have an error in your TS (like the red line under beta), you should not expect tstl to produce correct output.

**Comment by Toliak** [comment]
That works, thank you
