### ISSUE TITLE
Crash when hoisting inside a switch statement

### ISSUE THREAD

**Issue by tomblind** [TypeScriptToLua/TypeScriptToLua#1099]
```ts
let x = 0;
switch (x) {
    case 1:
        hoisted();
        break;
    case 2:
        function hoisted() {
            console.log("hoisted");
        }
        break;
}
```

It looks like hoisting inside a switch statement causes a crash inside TSTL:
```
Exception has occurred: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  nativeAssert(value, message)
   at Object.assert (utils.js:67:5)
    at hoistVariableDeclarations (transformation\utils\scope.js:157:21)
    at Object.performHoisting (transformation\utils\scope.js:113:14)
    at Object.transformSwitchStatement [as transform] (transformation\visitors\switch.js:60:26)
    at TransformationContext.transformNode (transformation\context\context.js:44:62)
    at transformation\context\context.js:70:58
    at Array.flatMap (<anonymous>)
    at TransformationContext.transformStatements (transformation\context\context.js:70:40)
    at Object.transformSourceFileNode [as transform] (transformation\visitors\sourceFile.js:29:63)
    at TransformationContext.transformNode (transformation\context\context.js:44:62)
```

**Comment by thejustinwalsh** [comment]
This playground illustrates what may be happening when you comment out the call to hoisted();
https://typescripttolua.github.io/play/#code/DYUwLgBAHhC8EAYDcAoAzgdwJZgMYAsIAKKASggG8UIaJcBDNECARgC5rauB6b-AeyxowIACZFSqLlwBGAJxD0A1lNoMmEAEwdptAGYBXAHa4wWfkYgChI8eSq7duC2n6gAdMH4BzIgCJrYTE-SU5dAF8w6XlFFRRwoA

**Comment by thejustinwalsh** [comment]
Testing this bug now, and hitting a couple of issues, though not sure of the root cause yet...

The error is being generated from this line:
https://github.com/TypeScriptToLua/TypeScriptToLua/blob/a6a89dfd0a72d10207ecbd2088acd89d2390723b/src/transformation/utils/scope.ts#L197

That line was added in: https://github.com/TypeScriptToLua/TypeScriptToLua/pull/762/files with the removal of `var`.

By changing that line to `if (index < 0) continue;` I can pass all the hoisting tests, and not blow up on the assert. However, the output from the function hoisting appears to be stripping full blocks of code.

For instance, in the test above, the label `____switch3_end` is now being removed from the statement list.

When running this sample through PR #1098 I hit the same assert, and the results of commenting the assert out are missing statement bodies.

**Comment by tomblind** [comment]
I've been poking at this one as well, and it's a bit complicated. There's a couple of issues at play:
- Hoisting fails in switch clause statements because they are wrapped in `do...end` blocks, so the code that moves statements around misses them entirely
- There's an issue where functions are actually being re-hoisted a second time since they are also seen as variables. The fact that this hasn't broken anything before is a bit of luck, but fixing the first issue causes this to become a real problem.

I have some potential fixes in the works, but those would have to be re-done for the new switch-case PR. It would probably be better to get that PR merged in first, then fix these issues with the new implementation instead of wasting time fixing it on the old one.

**Comment by thejustinwalsh** [comment]
I am not entirely sure why the clause statements are wrapped in `do...end`, I would think that technically the switch statement itself should be a scope, and that each clause is not lexically scoped unless specifically wrapping in `{` `}` parens.

That being said even if the auto lexical scoping of each clause is removed, the hoist would still need to handle it, for when the user does scope it themselves.

In #1098 I just kept the `do...end` wrapping because it was already there, without giving it any thought initially.

**Comment by tomblind** [comment]
I'm not sure why the blocks were used in the current implementation, but #1098 uses if statements which will have the same scoping effect and still need to be dealt with regarding hoisting.

Good point about the entire switch needing scope, though. I just tried and this example actually produces incorrect results, since we don't scope the entire switch right now:
```ts
function test() {
    let x: number = 0;
    let y = 1;
    switch (x) {
        case 0:
            let y = 2;
    }
    console.log(y); // Prints 1 in TS, prints 2 in TSTL
}
test();
```
