### ISSUE TITLE
Feature request - new compiler option - noImplicitGlobalVariables

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1119]
Edit - I renamed this issue; see discussion below.

In Lua land, regardless of what file you are working in, you always have to prepend your variables with `local` in order to avoid them from becoming a global variable. This is annoying, because you almost never want to create a global variable.

```lua
-- in file: foo.lua
local foo = "bar";
```

Most of the time, TSTL does not have this problem, which is great.
In TSTL land, you just declare normal variables, and they are almost always local.

```ts
// in file: foo.ts
const foo = "bar"; // Will transpile to the previous code snippet
```

However, there are two exceptions:
1) when `luaBundle` mode is turned off, any variables/functions in a file called "main.ts" or "init.ts" will automatically get turned into globals
2) when `luaBundle` mode is turned on, any variables/functions in the specified bundle entry point file will automatically get turned into globals

This is a hidden "gotcha" for TSTL users. I've been happily using TSTL for almost an entire year now, and only discovered this behavior recently. Unbeknownst to me, global variables were being created and causing run-time errors in production. ><

In a way, this behavior does make sense, because if I typed `const foo = "bar";` into a `<script>` tag on a webpage, that would obviously create a global variable. So, I think that TSTL is trying to mimic that behavior.

With that said, I think there is room for improvement here. If TSTL only creates global variables in some situations, and doesn't create global variables in other situations, this is confusing for end users. A better default might be for TSTL to just always output local variables, even in the above two situations. This helps prevents users from shooting themselves in the foot.

Consider that if an end-user is in a file called "foo.ts" and they want to create a global variable, it would look like this:

```ts
declare let foo: string;
foo = "bar";
```

Essentially, I am requesting that this global-variable-declaration-format is necessary across the board, for all TSTL files.

I think it's a good default behavior to have because using a global variable is the exception, rather than the norm. One typically only creates a global variable if they are explicitly exposing functionality to the outside world. And any particular program will only need to have a few global variables in total.

**Comment by Cheatoid** [comment]
I was actually writing a proposal that has to do with locals on top-level scope.
Very similar to what you're talking about here. Now I am not sure whether I should merge my proposal with this here, or create a new issue for it.
To begin with, both of your example snippets are looking wrong to me:
```typescript
const foo = "bar";
```
If this is the whole code you're transpiling, then TSTL won't emit it as `local foo = "bar"`, because `foo` is a variable on top-level scope.
[See this on playground](https://typescripttolua.github.io/play/#code/MYewdgzgLgBAZiEMC8MBEAjAhgJzQbiA).
And also your last snippet contains an error, the second line should read `foo = "bar";` not `string = "bar";`.

-----

Observe these:
[**Sample A:**](https://typescripttolua.github.io/play/#code/PQKhAIAEDsHsGUCmAbAZgSWgMQJbMeCMAFD4Au4O0ZiATtAIbIDSiAngFzjQCuAtgCM64AD7ge0ACaJUVRJIDcxAMaxoAZwoBzZLAFcAMjwYAVBgPzgAvOAD6AcXAN1T6GyU69AOnWIyACgAiKhwyHCYcAC9EVjZAgBpwfwBKawA+cABvYnBKajpGFnZrPJp6JljwAH4q8D4GMgALL1oGKVg+FKUAX2SFIA)
> All variables on top-level are treated as global (`glob` & `internalKey`). Surprise.

[**Sample B:**](https://typescripttolua.github.io/play/#code/PQKhAIAEDsHsGUCmAbAZgSWgMQJbMeCMAFADex44+ALuDtNYgE7QCGyA0ogJ4Bc40AK4BbAEbNwAH3CDoAE0Sp6iOQG4K4AMaxoAZ1oBzZLFH8AMoNYAVVqPzgAvOAD6AcXCtdH6N3WUjJgB0uojUABQARPQ41DjsOABeiFzcEQA04GEAlI4AfODklJT0jCzsKY50DMxsnDzgAPwN4MKs1AAWgUys8rDC2X7gAL5Z6kNAA)
> Notice the use of `{ }`, which creates a separate local scope and makes `glob` & `internalKey` no longer a part of top-level scope.

[**Sample C:**](https://typescripttolua.github.io/play/#code/PQKhAIAEDsHsGUCmAbAZgSWgMQJbMeCMAFD4Au4O0ZiATtAIbIDSiAngFzjQCuAtgCM64AD7ge0ACaJUVRJIDcxAMaxoAZwoBzZLAFcAMjwYAVBgPzgAvOAD6AcXAN1T6GyU69AOnWIyACgAiKhwyHCYcAC9EVjZAgBpwfwBKawA+cABvYnBKajpGFnZrPJp6JljwAH4q8D4GMgALL1oGKVg+FKUAX2SlRAAPAAdYWgpM7qA)
> Notice the use of `export {}`, this actually tends to be a solution, it marks everything as local on top-level, but it comes with a side-effect which can be unwanted in some circumstances, that is it creates and returns an empty table.

I don't think this has anything to do with `luaBundle`; Even if it does, as shown with the samples above, any variable on top-level scope is always being treated as a global except in the case of sample B & C.
In my (upcoming) proposal, I suggest to introduce a new *decorator* (or whatever such thing is being called, i.e. `/** @noSelfInFile */`):
- `/** @localOnTopLevel */`

There's actually more to this, that I think I will further try and describe within my proposal (I guess I will make a separate issue after all).

By the way, there is a relevant discussion over at the Discord server.

**Comment by Zamiell** [comment]
> If this is the whole code you're transpiling, then TSTL won't emit it as local foo = "bar", because foo is a variable on top-level scope.

It's not; see the code comment immediately preceding the line in question.

> your last snippet contains an error, the second line should read foo = "bar"; not string = "bar";

You're right. I fixed that.

**Comment by Perryvw** [comment]
This is very intentional behavior, and matches the TypeScript/JavaScript scoping rules as @Zamiell remarked, and more importantly the way the type system sees the code. In your use cases, this might not be useful, but there are other use cases that depend on this behavior. For those people this would be a major breaking change for what I see to be little benefit.

Whichever option we choose, there will always be somebody unhappy, and at least in the current setup we are consistent with what the TypeScript type checker thinks of the code. Would need a VERY good reason to adjust this.

**Comment by Cheatoid** [comment]
> For those people this would be a major breaking change for what I see to be little benefit.

It would not be a breaking change at all, because what I am proposing is that you would have to manually write/enable `/** @localOnTopLevel */` (a new decorator/config option) in order to opt-out from this "everything is global on top-level by default" behavior. In other words, it would make everyone happy.

**Comment by Zamiell** [comment]
> This is very intentional behavior, and matches the TypeScript/JavaScript scoping rules as @Zamiell remarked, and more importantly the way the type system sees the code. In your use cases, this might not be useful, but there are other use cases that depend on this behavior. For those people this would be a major breaking change for what I see to be little benefit.

> Whichever option we choose, there will always be somebody unhappy, and at least in the current setup we are consistent with what the TypeScript type checker thinks of the code. Would need a VERY good reason to adjust this.

Understood.
Based on this, consider this issue to now be a feature request for a new compiler option: `noImplicitGlobalVariables`
I will rename the issue accordingly.
Would you be opposed to this Perry?
