### ISSUE TITLE
afterPrint from the latest patch doesn't work

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1236]
repro: https://github.com/Zamiell/tstl-bug

**Comment by GlassBricks** [comment]
Some investigation:
The issue arises when using bundles. The bundle uses processed file's `sourceMapNode` instead of `code`, so a change to `code` in the plugin is lost.

We should either change this behavior, or document that `sourceMapNode` should be modified instead of 
`code` in plugins, when bundle is enabled. Or, we should remove the `code` field/make it readonly to avoid this confusion/inconsistency.
