### ISSUE TITLE
__TS__Iterator is incorrectly used for LuaTables

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1244]
Steps to reproduce:

```ts
const a = new LuaTable();
const entries = [...pairs(a)];
```

Here's a link to this code snippet on the TSTL playground: https://typescripttolua.github.io/play#code/MYewdgzgLgBAhjAvDMBTA7jAMgVzgFTgCMAbVACgEoBuAKFEllTCgCcBLVCJGAbQDpBABzjtWEcnEoBdOkA

**Comment by Perryvw** [comment]
After investigating this, this is a more tricky case than I first thought. The obvious Lua translation does not make sense here:
```lua
local tbl = {a=2,b=3}
local tbl2 = {pairs(tbl)} -- tbl2 is now { [1] = next, [2] = tbl }
```

Instead, we would have to consider translating to something like :
```lua
local tbl = {a=2,b=3}
local tbl2 = __TS__LuaIteratorToArray(pairs(tbl))
```
Which would mean we also have to distinguish between `LuaIterator<LuaMultiReturn<>>` and other `LuaIterator<>`, because one would lead to an array of arrays, while the other is just one flat array of items.

Or we could just disallow this case altogether, and just force users to use
```ts
Object.entries(tbl)
```
