### ISSUE TITLE
Different lualib versions are not resolved from lua_modules packages

### ISSUE THREAD

**Issue by backtolife2021** [TypeScriptToLua/TypeScriptToLua#1265]
before:
![image](https://user-images.githubusercontent.com/24669431/165092955-c20ea394-32ad-4dfe-818c-25a7385053ac.png)

after:
![image](https://user-images.githubusercontent.com/24669431/165094070-b7e2a31d-aed0-479c-8e05-bef578bfcd23.png)

This makes the module untraceable：
![image](https://user-images.githubusercontent.com/24669431/165094256-8eb2a236-41dc-4890-9339-d05598daa6bc.png)

repo: https://github.com/backtolife2021/zaza

**Comment by Perryvw** [comment]
This was intentional, used node_modules packages are supposed to be in the lua_modules directory in the out directory. It seems maybe the code of the package needs to be regenerated with the latest tstl version to correct for the new lualib usage we have now.

Ideally the lualib used by the package should be distributed as part of the package, that seems to be a bug for now.
