### ISSUE TITLE
noSelf ignored for lambda signatures defined in nested extended type

### ISSUE THREAD

**Issue by felixhirt** [TypeScriptToLua/TypeScriptToLua#1390]
lambda signatures defined in nested types ignore the noSelf option, as seen in the example:

https://typescripttolua.github.io/play#code/PQKhAIAEDsHsGUCmAbAZgSWgMQJbMeGMAFAAuAngA4EBKiA5jgM6mIBOiAJgMKwC2fAIbRO4ALzgAFADpZgtvSYAucMPIBtALoBKcQD5V0csTJUCvAcJ6xk+AMakcsaOPB07sNpwA8LNjmh6ABo3BmZWDmtLET0TCmpwbj5OAEZ4HHpoQVIAVw5XSXlFFQBvcAAFeUE+ZXA-APotAG5weHJoOxV6wPAAX10xA276OLMK+UdBW3J4QVRECyERXltEBycXCUWrFftHZ3AAMnAS4nBE5JSVJNT0zOy8xDPwYGBwUgALZnBUHI79lwfQRMOooVAAfkhzxuACYVIUFLUypU2NVasNmq12p06qR-D1+vpcfiRr0TL9-htwAARWBMeC5VCoSQeaKcZQoybTWbzbbLGx7DbaU7nc6spbs6Q3FKSEootFKdQAIiVmiCbQ6SiVGrsSv6zzF-AlTClyRhsvlNUVKrVOq1Or12gN4HFVhNNwAzBaqlblar1dj7djHcQyUA

typescript-to-lua version 1.12.0

**Comment by Perryvw** [comment]
Looking at this again, this is expected behavior. You wrote
```ts
type PartiallySafeCommandCollection = CommandCollection & {
  Cmd2: (args: { Params: string[]; Sync: string }) => string;
}
```
Which is the same as 
```ts
interface ICmd2 {
  Cmd2: (args: { Params: string[]; Sync: string }) => string;
}
type PartiallySafeCommandCollection = CommandCollection & ICmd2;
```
Since `ICmd2` is not marked with `@noSelf`, its content functions by default will be considered to have a self parameter. The `noSelfInFile` only applies to function definitions in the root scope, not recursively into interfaces, so that does not apply here.

The `noSelfInFile` does however apply to the `RegisteredCommand` function definition (which is in root scope), so if  you were to make it
```ts
interface ICmd2 {
  Cmd2: RegisterCommand;
}
type PartiallySafeCommandCollection = CommandCollection & ICmd2;
```
That would would.

**Comment by felixhirt** [comment]
Ah, makes sense. Thanks for clarifying!
