### ISSUE TITLE
DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1450]
When using TSTL on the latest version of TypeScript, it produces this warning:

> DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead

**Comment by code-luochen** [comment]
I tried it and it didn‘t work

**Comment by Zamiell** [comment]
What version of TSTL are you using?

**Comment by code-luochen** [comment]
Sorry ,I used umi. thank you. I'll think of something else




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TypeScriptToLua/TypeScriptToLua"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月26日(星期六) 晚上9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TypeScriptToLua/TypeScriptToLua] DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead (Issue #1450)





 
What version of TSTL are you using?
