### ISSUE TITLE
`nil,` is being prefixed to functions

### ISSUE THREAD

**Issue by Z3rio** [TypeScriptToLua/TypeScriptToLua#1487]
`nil` seems to be automatically being added as a parameter to functions where it shouldn't be added.
![image](https://github.com/TypeScriptToLua/TypeScriptToLua/assets/54480523/4de89461-9422-4e3b-8118-ccbeab59c588)
![image](https://github.com/TypeScriptToLua/TypeScriptToLua/assets/54480523/99e50dca-f7b2-4385-82f5-b72f3a691385)

I've read about this perhaps being the `self`/`this` reference, if so, how do I get rid of it? Since these functions break due to this fact.

**Comment by Zamiell** [comment]
did you read [this page](https://typescripttolua.github.io/docs/the-self-parameter) yet?

**Comment by Z3rio** [comment]
> did you read [this page](https://typescripttolua.github.io/docs/the-self-parameter) yet?

That does not seem to apply to functions outside of your own project :)

**Comment by Z3rio** [comment]
I have been able to get around this by modifying TSTL's code and adding my own checks, although I do not really believe that is a great solution, so I would still highly appreciate suggestions.

**Comment by Zamiell** [comment]
> Yeah, but that does not seem to apply to functions outside of your own project

are you talking about upstream lua? are you typing your own definitions?

**Comment by Z3rio** [comment]
> > Yeah, but that does not seem to apply to functions outside of your own project
> 
> are you talking about upstream lua? are you typing your own definitions?

I'm making add-ons for a game which supports Lua and JS.
Whereas I need the files to be in Lua, but would really love to still be able to use TS.

So the functions I'm using are related to that game and defined in these npm packages:
https://www.npmjs.com/package/@citizenfx/client
https://www.npmjs.com/package/@citizenfx/server

Hence why the functions aren't defined in my local project files and most likely why it doesn't work.

**Comment by Zamiell** [comment]
if the game supports JS then why are you using TSTL at all? can't you just use typescript and use the normal TS compiler to transpile to JS?

**Comment by Z3rio** [comment]
> Whereas I need the files to be in Lua, but would really love to still be able to use TS.
From my previous message ^^


The game requires Lua for quite a lot of functionalities, especially for publishing your projects, hence why I would need to use Lua :) I already use Ts -> JS where it is possible.

**Comment by Zamiell** [comment]
can you post a playground that illustrates the problem?

**Comment by Z3rio** [comment]
https://github.com/Z3rio/fivem-tstolua/tree/08f0d4ea04bd2beee8c4944e9c62c25efeced630

**Comment by Z3rio** [comment]
main directory -> npm run build
(Ignore ui directory)

**Comment by Z3rio** [comment]
Seems to be happening due to the fact that @citizenfx/client's type def's don't include `this: void`

Example type def
![image](https://github.com/TypeScriptToLua/TypeScriptToLua/assets/54480523/b28c0cf5-d517-4ece-a41a-aa9a5b3dec49)

**Comment by Perryvw** [comment]
This is funny expected behavior. In JS, every function call will pass the `this` object as a hidden extra argument by default. This means that in the normal case, there is never any need to specify this behavior when making declarations for JS (which this seem to be).

By contrast, in Lua there is no hidden variables being passed around. This means tstl will need more information to decide wether to call your function as an object method (with a `this` object, or with `:` instead of `.`) or not. This information we get from the declarations.

If nothing is specifically specified, we assume your code works like the JS implicitly specify: All function calls get a hidden `this` object. The declarations you are using here are simply lacking the information tstl requires to make a correct translation.
