### ISSUE TITLE
tsconfig.spec.ts fails in MacOS, because /var is actually located in /private/var

### ISSUE THREAD

**Issue by aabajyan** [TypeScriptToLua/TypeScriptToLua#1535]
I think having something like `fs.realpathSync` will solve the issue. I will test this and create a pull request later today.

```
  expect(received).toBe(expected) // Object.is equality

    Expected: "/var/folders/l1/q852l81d1lv95zhblgdvf0gr0000gn/T/tstl-test-FXslwE/tsconfig.json"
    Received: "/private/var/folders/l1/q852l81d1lv95zhblgdvf0gr0000gn/T/tstl-test-FXslwE/tsconfig.js
```

**Comment by Perryvw** [comment]
After some digging seems like this is the problem: https://github.com/nodejs/node/issues/7545

We are calling process.cwd() returning the real path `/private/var`, while the test just does a simple path.join with `/var`, causing the mismatch.

Since Node.js seems not to be planning to fix this I think we can go ahead with your proposed fix.
