### ISSUE TITLE
Extend lualib import options

### ISSUE THREAD

**Issue by lolleko** [TypeScriptToLua/TypeScriptToLua#155]
Additional options:

- `inlineLocal` inlines the function add the top of a file as local variables (maybe change inline to inlineGlobal when adding this)
- `requireSingle` (maybe use a better name for this): requires each feature via a separate file.

**Comment by lolleko** [comment]
Add manual import option (comment in #71)

**Comment by Janne252** [comment]
I think the inlined functions should be placed at the top of the file in case the file uses the features (e.g. ternary operation) on module level (not inside a scope), as demonstrated below:

```lua
local value = SomeFancyInlinedFunction();

-- stuff

function SomeFancyInlinedFunction()
    
end
```

Results in `attempt to call global 'SomeFancyInlinedFunction' (a nil value)` because `SomeFancyInlinedFunction` is referenced before its declaration. Lua doesn't hoist variables like JavaScript does!

**Comment by lolleko** [comment]
Superseded  by #653
