### ISSUE TITLE
Using the luaBundle option with a single Typescript file causes your code to run twice.

### ISSUE THREAD

**Issue by spidunno** [TypeScriptToLua/TypeScriptToLua#1558]
If you try to build one typescript file with the luaBundle option, all of the code in that file executes twice.

The issue goes away as soon as you import or export anything.

**Comment by Perryvw** [comment]
Problem is the faulty ternary conditional shorthand we are using in the bundle require: `(select("#", ...) > 0) and module(...) or module(file)`, if the module has no imports or exports and the first `module(...)` call is executed and returns nil (due to there being no imports/exports), that causes the second `module(file)` call also to be executed

**Comment by Z3rio** [comment]
Sounds interesting, any playground repro link, or such?

**Comment by Perryvw** [comment]
Playground doesn't bundle so won't reproduce, but a single typescript file with just `print("hi")` and bundling enabled should reproduce. I guess it also requires passing in some varargs at the top level

**Comment by Z3rio** [comment]
> Playground doesn't bundle so won't reproduce, but a single typescript file with just `print("hi")` (or I guess `console.log("hi")` and bundling enabled should reproduce. I guess it also requires passing in some varargs at the top level

Ah, okay, thanks, I'll see if I can find some time to have a look at it.

Thought it would be harder to reproduce than that, considering the issue has just now been reported.

**Comment by Perryvw** [comment]
> Thought it would be harder to reproduce than that, considering the issue has just now been reported.

I think this issue does not really occur because if you are bundling, you are probably importing files, otherwise what is the point of bundling a single file. Therefore it requires this specifically set up example to cause the problem in the first place. With normal usage I don't really expect this to happen.

Still, it's a bit of a gotcha especially for newcomers, and should be easy to fix with just a regular if statement instead of the ternary.

**Comment by spidunno** [comment]
> Therefore it requires this specifically set up example to cause the problem in the first place. With normal usage I don't really expect this to happen.

Unfortunately, it happened. Within normal usage.

**Comment by Z3rio** [comment]
> if you are bundling, you are probably importing files

I think normal usage would entail actually importing files.
Judging from " if you are bundling, you are probably importing files".

But yeah, no worries, me, Perry, or someone else will have a look at it sometime soon :)

**Comment by spidunno** [comment]
I should probably mention that my intended use  case is a template that is meant to be used by people that know nothing about TypescriptToLua. They shouldn't need to know what config setting to change once they add another file, so having bundle mode work even without any imports makes sense here, at least to me.
