### ISSUE TITLE
Postbuild script in package.json does not work

### ISSUE THREAD

**Issue by Kilkenni** [TypeScriptToLua/TypeScriptToLua#1565]
Subj.

Thanks for TSTL!
Anyway, I've added "prebuild" and "postbuild" scripts (with simple "echo stuff") to package.json. When `npm run build` is called, prebuild is triggered just fine (prints into console). However, postbuild script doesn't trigger automatically unless explicitly called via `npm run postscript` by the user.

Am I doing something wrong?

Update: Postbuild seems to not work if emit throws _any_ errors (even if these errors do not prevent emit in any way). Is this the correct behavior?
(I generally get errors due to "undefined globals" because I have no typescript definition files for my Lua environment, these do not influence post-emit files in any way for obvious reasons)

**Comment by Perryvw** [comment]
> Update: Postbuild seems to not work if emit throws any errors (even if these errors do not prevent emit in any way). Is this the correct behavior?
(I generally get errors due to "undefined globals" because I have no typescript definition files for my Lua environment, these do not influence post-emit files in any way for obvious reasons)

Errors (not warnings) will return a failure exit code, so that if you run tstl as CLI script, your operation fails when there are errors in the compilation. This is the same as basically every CLI tool (pretty sure tsc will behave exactly the same here).

So yeah, you'll have to fix your errors by adding declaration files for your lua environment.
