### ISSUE TITLE
Module import on sandboxed systems.

### ISSUE THREAD

**Issue by Istar-Eldritch** [TypeScriptToLua/TypeScriptToLua#292]
Hi, I'm writing the type definitions for the Minetest Mod API. Minetest runs all its mods sandboxed so they can't access each others source code, for this reason, they restricted the `require` function. Among the community, they usually use `dofile` instead. 

`tstl` uses `require` while transpiling from TypeScript imports, I was exploring the possibility of providing a flag to tstl to load modules using `dofile` instead, and while I do not have yet a clear idea of how to do it, I do believe its possible.

In the meanwhile I found an alternative by using `luapak` to bundle all the modules in a single file.

I wanted to report this issue to clarify two points:
- Is this functionality something that would benefit other users appart from the Minetest folks?
- If we find out that we don't want to support this functionality in `tstl`, would it be possible to do this as an external module that extends `tstsl` instead of forking it?

**Comment by lolleko** [comment]
We are planning a plugin architecture that will allow you to basically add a custom "Target". https://github.com/Perryvw/TypescriptToLua/issues/179 

We are also planning on supporting typescripts transformers https://github.com/Perryvw/TypescriptToLua/issues/278

With those features you should be able to accomplish a custom require.

Can't give you an ETA tho, since this is a big change.

**Comment by SinZ163** [comment]
#357 would also mitigate this problem and its use case was for Tabletop Simulator, so you aren't alone.

**Comment by Perryvw** [comment]
Closing this since the new plugin infrastructure and also bundling was added.
