### ISSUE TITLE
Some functions are getting nil params at compile

### ISSUE THREAD

**Issue by ElronMacBong** [TypeScriptToLua/TypeScriptToLua#563]
I found two functions where are 1st nil parameters gets added into lua file, which aren't defined.
Will increase the list if i find new ones.
- print
- SendToServer

**Comment by Perryvw** [comment]
I [just updated](https://github.com/TypeScriptToLua/Dota2Declarations/commit/c4b5f541f0069bc35addd52aeaaa7858a0f4de85) the declarations with the latest version I had locally, these should work better for you. You can get them from https://github.com/TypeScriptToLua/Dota2Declarations.

Next time you have issues with the dota declarations, please make an issue there instead of on this repo, this is just for tstl ;)

**Comment by ElronMacBong** [comment]
Ah k, wasnt aware about that.

**Comment by RobLoach** [comment]
For those following along at home, you'll want [@noSelfInFile](https://github.com/TypeScriptToLua/TypeScriptToLua/wiki/Compiler-Directives#noselfinfile)
