### ISSUE TITLE
`/** @noSelfInFile */` cannot work correctly

### ISSUE THREAD

**Issue by zaoqi** [TypeScriptToLua/TypeScriptToLua#722]
a.ts
```
/** @noSelfInFile */
((x=>x) as any)(0)
```
```
$ npx tstl a.ts
```
a.lua
```
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
(function(x) return x end)(_G, 0)
```

**Comment by ark120202** [comment]
`@noSelfInFile` isn't meant to affect anything at call position, it's supposed to be used on signature declaration. So, if we'd want to support it, it'd have to work like that:
```ts
/** @noSelfInFile */
declare const foo: any;
```
```ts
foo(); // => foo()
```

Which is more complex since I don't think we have enough data about declaration in that case.

Of course we could try to support this exact case, but I don't see it being any more meaningful than trying to support `('foo' as any).slice(1)`.

**Comment by Perryvw** [comment]
The example is a little confusing since it looks like a directive on that line, but really that directive is at the top of the file and affects everything in it.

This looks like an actual bug, the inline function is correctly ommitting the self parameter, but the call somehow still has it, breaking functionality.

**Comment by Perryvw** [comment]
After discussing this with @ark120202 on discord we have decided to close this as we do not want to support this.

### Summary of the discussion:

In the snippet:
```ts
/** @noSelfInFile */
((x=>x) as any)(0)
```
The directive `/* @noSelfInFile */` is applied to all declarations in that file. This results in `x => x` translating correctly to `function(x) return x end`. The function however is the cast to `any`, which is declared by default (so not in this file) and thus **any is not affected by `/* @noSelfInFile */`**. This means that functions typed as `any` will always use default behavior and include the self argument.
