### ISSUE TITLE
transpiled add self error

### ISSUE THREAD

**Issue by cloudfreexiao** [TypeScriptToLua/TypeScriptToLua#753]
```ts
export declare namespace skynet {

    function start(startfunc: () => void): void;

    function starttime(): number;

    function now(): number;

    function timeout(ti: number, f: (...args: any[]) => any): void;
}

skynet.start = () => {
    print(skynet.starttime());

    skynet.timeout(100, () => {
        print("in 100 =>", skynet.now());
    });
};
```
transpiled out
```lua
local ____skynet = require("skynet")
local skynet = ____skynet.skynet
skynet.start = function()
    print(
        skynet:starttime()
    )
    skynet:timeout(
        100,
        function()
            print(
                "in 100 =>",
                skynet:now()
            )
        end
    )
end
```
the skynet.starttime() and skynet.timeout() is add self

**Comment by Perryvw** [comment]
For future reference, here is the discussion from the discord:

That's intentional behaviour. There are four things you can do:
1) Give the functions a first argument `this: void` to indicate they have no 'self'.
2) Put `/** @noSelf */` above or in front of the function.
3) Put /** @noSelfInFile */ at the top of the file to apply the previous 2 options to all declarations in that file.
4) Use the `--noImplicitSelf` command line flag or set `noImplicitSelf: true` in tsconfig to remove this behavior from the project completely.
