### ISSUE TITLE
Promise Transfer Lua

### ISSUE THREAD

**Issue by mmc1993** [TypeScriptToLua/TypeScriptToLua#772]
你好, 我发现你没有做Promise To Lua的转换, 正巧我实现过相关的功能, 能否集成到你的项目中?
https://github.com/mmc1993/Lua-Async

Hello, I found that you did not make the transformation of Promise To Lua. I happened To have realized relevant functions. Could you integrate them into your project?
https://github.com/mmc1993/Lua-Async

**Comment by ark120202** [comment]
We already had a PR with a very close-to-spec `Promise` implementation in pure TS: https://github.com/TypeScriptToLua/TypeScriptToLua/pull/380/files#diff-7cd9fcd13194530e7f589449d1df0203. Your library looks more like some event loop implementation rather than a `Promise`, which is out of scope of the promise itself, but can be integrated with it (for example with `Promise._setRunAtNextTickFunction` in that PR)

I'm going to close it, because we already have an issue tracking promise support - #147.
