### ISSUE TITLE
Instantiation of userdata types declared as classes (0.30)

### ISSUE THREAD

**Issue by frank256** [TypeScriptToLua/TypeScriptToLua#792]
Hi,
after upgrading to 0.30, the instantiation of userdata types declared as classes does not work anymore.
Basically, I have bound a C userdata type `UserDataClass` and a corresponding factory function to Lua so that calling `UserDataClass.new()` would produce a userdata instance on which I would then call `instance:classMethod()` in Lua.
I have declared these types by simply writing
```typescript
declare class UserDataClass {
   classMethod();
}
```
and it would "just work" (which has been quite awesome).
How can I re-enable this functionality in 0.30?
Could this be considered a bug? 
I use this stuff a lot and it basically prevents me from upgrading right now.
Thank you!

**Comment by Perryvw** [comment]
This change was intentional. In general we would advise against declaring stuff as classes if they do not use the typescript-to-lua class implementation.

If you want to stick to this current pattern, I would suggest simply declaring your `new`  factory method as a static method on your declaration and replace `new UserDataClass()` with `UserDataClass.new()`:
```ts
declare class UserDataClass {
   classMethod();
   // Add factory method
   static new(): UserDataClass;

   /**
    * Use UserDataClass.new() instead.
    */
   private constructor(); // Disallow regular constructor by making it private
}

const inst = new UserDataClass(); // TS Error, constructor is private

const inst_new = UserDataClass.new();
```
[Try it on the playground](https://typescripttolua.github.io/play.html#src=declare%20class%20UserDataClass%20%7B%0A%20%20%20classMethod()%3B%0A%20%20%20%2F%2F%20Add%20factory%20method%0A%20%20%20static%20new()%3A%20UserDataClass%3B%0A%0A%20%20%20%2F**%0A%20%20%20%20*%20Use%20UserDataClass.new()%20instead.%0A%20%20%20%20*%2F%0A%20%20%20private%20constructor()%3B%20%2F%2F%20Disallow%20regular%20constructor%20by%20making%20it%20private%0A%7D%0A%0Aconst%20inst%20%3D%20new%20UserDataClass()%3B%0A%0Aconst%20inst2%20%3D%20UserDataClass.new()%3B%0A)

If you want to avoid risking our class implementation influencing any of your code, I would suggest defining a completely separate factory method and using an interface:
```ts
declare interface UserDataClass {
   classMethod();
}
declare function NewUserDataClass(this: void): UserDataClass;

const inst = NewUserDataClass();
```
[Try it on the playground](https://typescripttolua.github.io/play.html#src=declare%20interface%20UserDataClass%20%7B%0A%20%20%20classMethod()%3B%0A%7D%0Adeclare%20function%20NewUserDataClass(this%3A%20void)%3A%20UserDataClass%3B%0A%0Aconst%20inst%20%3D%20NewUserDataClass()%3B)

Hope this helps, please let us know if this works for you or if there are some other problems I have not thought of.

**Comment by Perryvw** [comment]
Closing this for now since no further action is planned.

**Comment by frank256** [comment]
Thank you for your helpful comments.

I've finally taken this slightly hacky approach to keep the Lua "standard" .new() function, not interfere with TSTL's classes, and have the constructor signature within the interface (which I somehow prefer):
```typescript
interface CtorFor<T extends { new(...args: any): T }> {
  new: (this: void, ...t: ConstructorParameters<T>) => T;
}  

declare interface UserDataClass {
 new(a: A, b: B, c: number): UserDataClass; // Some parameters.

 classMethod();
}

declare const UserDataClass: CtorFor<UserDataClass>; // Copy parameters from above.
```
