### ISSUE TITLE
Incorrectly resolving imports.

### ISSUE THREAD

**Issue by maxiy01** [TypeScriptToLua/TypeScriptToLua#917]
Hello there, I have problems with importing lua libraries.

Here's the situation: I'm using I'm using [this template](https://github.com/hazzard993/love-typescript-template) and try to add e.g. [lurker](https://github.com/hazzard993/tstl-lurker) to my project. when I write `import lurker = require('lurker')` in `main.ts`, everything is fine and it transpiles to `local lurker = require('lurker')` in lua code, but when I try do do the same thing in file in child directory, e.g. `src/some/folder/script.ts`, generated lua code will contain `local lurker = require('some.folder.lurker')` (instead of just `'lurker'`).

How to solve this problem? Thanks in advance.

**Comment by ark120202** [comment]
This definition module doesn't look right. Things that are declared with `declare module` are usually expected to have [`@noResolution`](https://typescripttolua.github.io/docs/advanced/compiler-annotations#noresolution) annotation. However generally this approach should be used only for modules provided by the environment.

For modules that are real .lua files (such as `lurker`) it's better to define them in a .d.ts file with the same path as the .lua file, exporting things directly (without `declare module`), and be imported using relative imports. Currently it's not perfect, because you'd need to have a separate script copying .lua files to output directory, and in order to put declarations into a shared module (`tstl-lurker`) its consumers would have to use `paths` option. #909 should make this approach much better, because `tstl-lurker` module would be able to distribute executable .lua file itself, which would be copied to the output directory at build time.

**Comment by maxiy01** [comment]
Thanks for your answer, looks like adding `@noResolution` to module did the trick. Even without copying lua file.

**Comment by weinixuehao** [comment]
@maxiy01 @ark120202 
I used the low api of the sdk to transpile to lua, using the function is transpile how to avoid this issue?
`"typescript-to-lua": "0.34.0" `is used by me
