### ISSUE TITLE
how can use this in java js engine？

### ISSUE THREAD

**Issue by qq1053831109** [TypeScriptToLua/TypeScriptToLua#987]
how can use this in java js engine？
i just need ts 2 lua in java, i dont need node.js

**Comment by Perryvw** [comment]
You can probably bundle all tstl code in some way like we bundle it for the website using webpack. You can then provide a custom EmitHost to implement file reads/writes like we do for the playground: https://github.com/TypeScriptToLua/TypeScriptToLua.github.io/blob/source/src/pages/play/ts.worker.ts#L25

Other than that the tool is mainly written for node and we do not actively support running it in other tools. I don't really get why you would want to run it in java instead of node.js to be honest.
